name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    name: Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        go: ['1.21']

    steps:
    - uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v4
      with:
        go-version: ${{ matrix.go }}
        cache: ${{ hashFiles('**/go.sum') != '' }}

    - name: Install Linux Dependencies
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y libgtk-3-dev

    - name: Install macOS Dependencies
      if: matrix.os == 'macos-latest'
      run: |
        if ! [ -f /Library/Developer/CommandLineTools/usr/bin/gcc ]; then
          xcode-select --install || true
        fi

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./... 